### ISSUE TITLE
Collect all validation errors and then fail

### ISSUE THREAD

**Issue by todvora** [Graylog2/JadConfig#126]
Current implementation stops with the first validation/parameter exception. If users have several problems in the configuration, they need to fix one by one and always restart the graylog server meanwhile. If we could collect all errors and only then fail, it would simplify initial setups significantly. 

Maybe it would be enough to adapt https://github.com/Graylog2/JadConfig/blob/main/src/main/java/com/github/joschi/jadconfig/JadConfig.java#L91 , instead of throwing exceptions collect them and then fail if there is at least one, throwing one wrapping all failures.

**Comment by bernd** [comment]
@todvora We could introduce an additional parse method that behaves like that. Changing the behavior of the existing `#process` method would be a breaking change.

**Comment by todvora** [comment]
Implemented in https://github.com/Graylog2/JadConfig/pull/127. Here it would need only a very tiny change, switching  from jadConfig.process() to jadConfig.processFailingLazily()
